config/routes.rb
Rails.application.routes.draw do
  resources :caretakers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caretaker.rb
class Caretaker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/caretakers_controller.rb
class CaretakersController < ApplicationController
  before_action :set_caretaker, only: %i[ show edit update destroy ]

  # GET /caretakers or /caretakers.json
  def index
    @caretakers = Caretaker.all
  end

  # GET /caretakers/1 or /caretakers/1.json
  def show
  end

  # GET /caretakers/new
  def new
    @caretaker = Caretaker.new
  end

  # GET /caretakers/1/edit
  def edit
  end

  # POST /caretakers or /caretakers.json
  def create
    @caretaker = Caretaker.new(caretaker_params)

    respond_to do |format|
      if @caretaker.save
        format.html { redirect_to caretaker_url(@caretaker), notice: "Caretaker was successfully created." }
        format.json { render :show, status: :created, location: @caretaker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @caretaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /caretakers/1 or /caretakers/1.json
  def update
    respond_to do |format|
      if @caretaker.update(caretaker_params)
        format.html { redirect_to caretaker_url(@caretaker), notice: "Caretaker was successfully updated." }
        format.json { render :show, status: :ok, location: @caretaker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @caretaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /caretakers/1 or /caretakers/1.json
  def destroy
    @caretaker.destroy

    respond_to do |format|
      format.html { redirect_to caretakers_url, notice: "Caretaker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caretaker
      @caretaker = Caretaker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def caretaker_params
      params.require(:caretaker).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caretakers_helper.rb
module CaretakersHelper
end

app/views/caretakers/_form.html.erb
<%= form_with(model: caretaker) do |form| %>
  <% if caretaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(caretaker.errors.count, "error") %> prohibited this caretaker from being saved:</h2>

      <ul>
        <% caretaker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/caretakers/edit.html.erb
<h1>Editing Caretaker</h1>

<%= render 'form', caretaker: @caretaker %>

<%= link_to 'Show', @caretaker %> |
<%= link_to 'Back', caretakers_path %>

app/views/caretakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Caretakers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @caretakers.each do |caretaker| %>
      <tr>
        <td><%= caretaker.name %></td>
        <td><%= link_to 'Show', caretaker %></td>
        <td><%= link_to 'Edit', edit_caretaker_path(caretaker) %></td>
        <td><%= link_to 'Destroy', caretaker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caretaker', new_caretaker_path %>

app/views/caretakers/new.html.erb
<h1>New Caretaker</h1>

<%= render 'form', caretaker: @caretaker %>

<%= link_to 'Back', caretakers_path %>

app/views/caretakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @caretaker.name %>
</p>

<%= link_to 'Edit', edit_caretaker_path(@caretaker) %> |
<%= link_to 'Back', caretakers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zoo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>